repos:
- repo: https://github.com/cmhughes/latexindent.pl
  rev: V3.15
  hooks:
  - id: latexindent-conda
    args: [-s, -w, -l, -m]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
