name: Build examples

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX example - basic
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/basic
        root_file: example.tex
    - name: Compile LaTeX example - twocolumn
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/twocolumn
        root_file: example.tex
    - name: Compile LaTeX example - general-trick_dummy-subfigure
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/general-trick_dummy-subfigure
        root_file: example.tex
