name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Compile LaTeX example - basic
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/basic
        root_file: main.tex

    - name: Compile LaTeX example - namecite
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/namecite
        root_file: main.tex

    - name: Compile LaTeX example - twocolumn
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/twocolumn
        root_file: main.tex

    - name: Compile LaTeX example - general-trick_dummy-subfigure
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/general-trick_dummy-subfigure
        root_file: main.tex

    - name: Compile LaTeX example - general-trick_dummy-subfigure-upper
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/general-trick_dummy-subfigure-upper
        root_file: main.tex
